# Generated by Django 2.0.4 on 2018-04-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart1',
        ),
        migrations.AlterModelTable(
            name='cart1',
            table='Cart1',
        ),
    ]
