# Generated by Django 2.0.4 on 2018-04-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180420_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart1',
            new_name='Cart',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
